[[input.prepend_keymap]]
  on   = [ "<Esc>" ]
  run  = "close"
  desc = "Cancel input"

[[manager.prepend_keymap]]
  on   = [ "l" ]
  run  = "plugin --sync smart-enter"
  desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
  on   = [ "<Enter>" ]
  run  = "plugin --sync smart-enter"
  desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
  on = [ "O", "e" ]
  run = """  shell --confirm 'emacs "$@"'  """
  desc = "Open in Emacs"

[[manager.prepend_keymap]]
  on = [ "T" ]
  run = "plugin --sync hide-preview"
  desc = "Toggle preview pane"

[[manager.prepend_keymap]]
  on = [ "g", "m" ]
  run = "[ -d \"/run/media/$USER\" ] && cd \"/run/media/$USER\""
  desc = "Go to mounted media"
