[manager]
sort_by = "natural"
sort_dir_first = true

[opener]
imv = [
	{ run = 'imv-dir "$@"', desc = "Open image in imv-dir", orphan = true, for = "linux" },
]

[open]
rules = [
	{ mime = "image/*", use = ["imv", "image"] },
]